# Generated by Django 4.2.7 on 2026-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='category',
        ),
        migrations.AddField(
            model_name='bag',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.category'),
        ),
    ]
