# Generated by Django 4.2.7 on 2026-05-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_bag_category_bag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='name',
        ),
        migrations.AddField(
            model_name='bag',
            name='categories',
            field=models.ManyToManyField(related_name='bags', to='products.category'),
        ),
    ]
