# Generated by Django 4.2.7 on 2026-05-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_bag_category_remove_bag_name_bag_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
