# Generated by Django 4.2.7 on 2026-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='category',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
