# Generated by Django 4.2.7 on 2026-05-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankqr',
            name='upi_id',
        ),
    ]
